name: metaseq-lite
channels:
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - python>=3
  - bedtools
  - samtools
  - ucsc-bedgraphtobigwig
  - ucsc-bigwigtobedgraph
  - ucsc-bigwigsummary
  - mysqlclient
  - gffutils>=0.9
  - matplotlib>=1.3.1
  - numpy>=1.15.*
  - pandas>=0.23.*
  - pybedtools>=0.8.*
  - scipy>=1.1.*
  - bx-python>=0.8.*
  - biopython
  - pysam
  - pyyaml
  - fisher>=0.1.*
  - cython
  - scikit-learn
  - nose
  - sphinx
  - ipython
  - ipython_genutils
  - ipywidgets
